services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.2.3
    container_name: anvil
    command: >
      anvil --host 0.0.0.0 --port 8545
            --chain-id 31337 --block-time 1
    ports:
      - "8545:8545"
    networks: [ evm-net ]

networks:
  celestia-net:
  evm-net:
